apiVersion: v1
kind: Service
metadata:
  name: secure-observable-service
  labels:
    app: secure-observable-app
spec:
  type: NodePort
  selector:
    app: secure-observable-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP